version: '3'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
